pattern = 'v0.1.%d'
types = ["Cargo"]
message-template = "Releasing {version}."

[artifact.mac]
paths = {"pagerduty-cli" = "mac/pagerduty-cli"}
compress = { name = "pagerduty-cli-mac.tar.gz", format = "tgz" }
target = "GitHub"

[artifact.linux]
paths = {"pagerduty-cli" = "linux/pagerduty-cli"}
compress = { name = "pagerduty-cli-linux-x86_64.tar.gz", format = "tgz" }
target = "GitHub"
